version_check_task:
  name: Test versiones go
  env:
    matrix:
      - GO_VERSION: 1.19
      - GO_VERSION: 1.18
  container:
    image: golang:${GO_VERSION}-alpine
  get_script: /usr/bin/make installdeps
  build_script: /usr/bin/make build
  test_script: CGO_ENABLED=0 go test ./...
