version_check_task:
  name: Test versiones go
  env:
    matrix:
      - GO_VERSION: 1.20-rc
      - GO_VERSION: 1.19.4
      - GO_VERSION: 1.18.9
  container:
    image: golang:${GO_VERSION}-alpine
  get_script: go get ./...
  build_script: go build ./...
