version_check_task:
  name: Test versiones go
  env:
    matrix:
      - GO_VERSION: 1.19
      - GO_VERSION: 1.18
  container:
    image: golang:${GO_VERSION}-alpine
  get_script: make installdeps
  build_script: make build
  tests_script: make test
