name: "Tests docker"
on:
  push:
    branches:
      - main
      - objetivo-5

jobs:
  docker-image-test:
    runs-on: ubuntu-latest

    steps:
      - name: La imagen es correcta
        run: docker run -t -v `pwd`:/app/test luistf24/trozo-de-panceta 
