name: "Tests docker"
on:
  pull_request:
    branches:
      - main
  push:
    paths:
      - "Dockerfile"

jobs:
  docker-image-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login Docker
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/trozo-de-panceta:latest

      - name: Test Docker
        run: docker run -t -v `pwd`:/app/test luistf24/trozo-de-panceta 
