name: "Tests docker"
on:
  push:
    branches:
      - main
      - objetivo-5

jobs:
  docker-image-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login Docker
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker
        run: docker build -t luistf24/trozo-de-panceta:latest .
      
      - name: Push Docker
        run: docker push luistf24/trozo-de-panceta:latest

      - name: Test Docker
        run: docker run -t -v `pwd`:/app/test luistf24/trozo-de-panceta 
